// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAis8xa_npQEVEyhStoVMVGZq-titcmH3M',
    appId: '1:555926188366:web:380671c6d874df9d392e1f',
    messagingSenderId: '555926188366',
    projectId: 'tailorfit-9ed20',
    authDomain: 'tailorfit-9ed20.firebaseapp.com',
    storageBucket: 'tailorfit-9ed20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSe2fwNDN0u23xym-SkBFvYbeppD6ynjw',
    appId: '1:555926188366:android:d42074b3a378684b392e1f',
    messagingSenderId: '555926188366',
    projectId: 'tailorfit-9ed20',
    storageBucket: 'tailorfit-9ed20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9fI0b7Rok5_-3rHNqEuLNaUjRdRXjnJM',
    appId: '1:555926188366:ios:0e68dd320ed90a89392e1f',
    messagingSenderId: '555926188366',
    projectId: 'tailorfit-9ed20',
    storageBucket: 'tailorfit-9ed20.firebasestorage.app',
    iosBundleId: 'com.example.tailorfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9fI0b7Rok5_-3rHNqEuLNaUjRdRXjnJM',
    appId: '1:555926188366:ios:0e68dd320ed90a89392e1f',
    messagingSenderId: '555926188366',
    projectId: 'tailorfit-9ed20',
    storageBucket: 'tailorfit-9ed20.firebasestorage.app',
    iosBundleId: 'com.example.tailorfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAis8xa_npQEVEyhStoVMVGZq-titcmH3M',
    appId: '1:555926188366:web:46ed0d58a331345e392e1f',
    messagingSenderId: '555926188366',
    projectId: 'tailorfit-9ed20',
    authDomain: 'tailorfit-9ed20.firebaseapp.com',
    storageBucket: 'tailorfit-9ed20.firebasestorage.app',
  );
}
